### ISSUE TITLE
Re-sizing of Q&A component for mobile

### ISSUE THREAD

**Issue by Tribalash** [MormontRFC2209/front-end-capstone#89]
The UI looks amazing and functions great on desktop. There is an issue when viewing on mobile 

<img width="600" alt="Screen Shot 2022-10-29 at 9 58 37 AM" src="https://user-images.githubusercontent.com/66389466/198841229-e9014e53-a7c5-4d42-8f6f-cfdc00a1660b.png">

We were able to get this to work better on mobile by setting media queries and changing the layout under a certain size. This was a little bit of nitpicking though because the site looks and works great on desktop!

**Comment by AnswerAye** [comment]
It now renders properly. Thanks!
