### ISSUE TITLE
Search of questions only searches questions that are currently rendered

### ISSUE THREAD

**Issue by Tribalash** [MormontRFC2209/front-end-capstone#91]
When searching for questions if the question is not rendered it will not be included in results
<img width="500" alt="Screen Shot 2022-10-29 at 10 07 18 AM" src="https://user-images.githubusercontent.com/66389466/198841861-4061c334-3623-4a40-a042-c7147055a787.png">

<img width="500" alt="Screen Shot 2022-10-29 at 10 11 07 AM" src="https://user-images.githubusercontent.com/66389466/198841897-ec977be5-46c3-4930-8ac4-6d375ffb5149.png">

I'm sure that this is due to the way state is managed and how questions are added when "More Questions" is clicked. This could be handled with a different state management approach for the questions.

**Comment by AnswerAye** [comment]
Fixed the variable used to iterate through the questions array and it now properly works, thank you!
